version: '3.8'
services:
  db:
    container_name: webapp
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '3001:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local